[package]
name = "twitchy-mcbotface"
version = "0.1.0"
edition = "2021"

[lib]
name = "tmbf"
path = "src/lib.rs"

[[bin]]
name = "twitchy-mcbotface"
path = "src/main.rs"

[dependencies]

thiserror = "~1.0"
anyhow = "~1.0"

glow = "0.11"
glutin = "0.28.0"
egui_glow = "0.17.0"
egui = { version = "0.17.0", default-features = false, features = [
  "convert_bytemuck",
  "single_threaded",
] }

ndi-sdk = { path = "/home/wayne/projects/rust-ndi" }
