[package]
name = "twitchy-mcbotface"
version = "0.1.0"
edition = "2021"

[lib]
name = "tmbf"
path = "src/lib.rs"

[[bin]]
name = "twitchy-mcbotface"
path = "src/main.rs"

[dependencies]

thiserror = "~1.0"
anyhow = "~1.0"

glow = "0.11"
glutin = "0.28.0"
egui_glow = "0.17.0"
egui = { version = "0.17.0", default-features = false, features = [
  "convert_bytemuck",
  "single_threaded",
] }

ndi-sdk = { path = "/home/wayne/projects/rust-ndi" }

twitch-irc = { version = "~4.0", features = [ "with-serde" ] }

tokio = { version = "~1.17", features = [
  "rt-multi-thread",
  "rt",
] }
futures = "~0.3"

# config serialization/deserialization
serde = "1.0"
serde_yaml = "0.8"

unicode-segmentation = "~1.9"
