build:
  cargo build

build-refactor:
  # requires cargo-limit to be installed
  reset
  (cargo lbuild --color=always 2>&1) | less -R

watchexec target:
  watchexec \
    -c \
    -e toml,rs,proto \
    -w justfile \
    -w ../router/proto/ \
    -w ../router/build.rs \
    -w ../router/Cargo.toml \
    -w ../router/src \
    -w ../router/Cargo.toml \
    -w ../cmdr/src \
    -w ../cmdr/Cargo.toml \
    --restart \
    just {{target}}

we-build-refactor:
  just watchexec build-refactor

we-build:
  just watchexec build
